baseURL = "https://www.fourjuaneight.com/"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "fourjuaneight"

[author]
  name = "Juan Villela"
  email = "hello@juanvillela.me"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  social = "fourjuaneight"

[params.meta]
  description = "Hi, I'm Juan and this is a site about Juan."

[outputs]
  home = ["html"]