baseURL = "/"
languageCode = "en-us"
title = "Clever Laziness"
copyright = " 2018 Clever Laziness"

enableRobotsTXT = "true"
enableEmoji = "true"

FootnoteReturnLinkContents = "↩"

[author]
  name = "[Juan](https://www.twitter.com/theverylastjuan)"
  email = "hi@cleverlaziness.com"

SectionPagesMenu = "main"

[permalinks]
  archive = "/:title/"

[[menu.main]]
  name = "Archive"
  weight = -120
  identifier = "archive"
  url = "/archive/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "License"
  weight = -110
  identifier = "license"
  url = "/license/"

[params.meta]
  keywords = "coding, productivity, automation"
  description = "A blog about coding and productivity"

[params]
  social = "theverylastjuan"
  OpenLinksInNewWindow = true

[outputs]
  home = ["html", "rss"]

[params.google.analytics]
    trackerID = "UA-103631497-1"