baseURL = "https://www.cleverlaziness.com/"
languageCode = "en-us"
title = "Clever Laziness"
copyright = " 2017 Clever Laziness"

enableRobotsTXT = "true"
enableEmoji = "true"

[author]
  name = "[Juan](https://www.twitter.com/theverylastjuan)"

SectionPagesMenu = "main"

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "License"
  weight = -110
  identifier = "license"
  url = "/license/"

[params.meta]
  keywords = "procrastination, automation, iOS, macOS, web, Apple"
  description = "A blog about automation and productivity"

[params]
  twitter = "cleverlaziness"
  Favicon = "favicon.ico"
  OpenLinksInNewWindow = true

  [params.social]
    facebook = "cleverlaziness"
    twitter = "cleverlaziness"

  [params.authors]
    [params.authors.Juan]

      name = "Juan"
      thumbnail	= "/static/logo.png"
      images = [{{ "/logo.png" | relURL }}]
      bio	= "The Empire did nothing wrong"
      email	= "cleverlaziness@gmail.com"

      [params.authors.Juan.social]
        github = "theverylastjuan"
        twitter	= "theverylastjuan"

[outputs]
  home = ["html", "rss"]
