baseURL = "https://www.cleverlaziness.com/"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Clever Laziness"

FootnoteReturnLinkContents = "↩"
SectionPagesMenu = "main"

# Pygments Syntax Highlighting
pygmentsUseClassic = false
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "lineseparator=<br>"
pygmentsStyle = "dracula"

[author]
  name = "Juan"
  email = "hi@cleverlaziness.com"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  social = "fourjuaneight"

[params.meta]
  description = "A blog about coding and productivity"
  keywords = "coding, productivity, development, front-end, automation"

[taxonomies]
  genre = "genre"
  category = "category"

[permalinks]
  articles = "/articles/:title/"
  bookshelf = "/bookshelf/:title/"
  genre = "/bookshelf/genre/:slug/"
  category = "/articles/category/:slug/"

[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true

[outputs]
  home = ["html"]
  section = ["html", "jsonfeed"]

[params.google]
  analytics = "UA-119777735-1"