baseURL = "http://www.cleverlaziness.com/"
languageCode = "en-us"
title = "Clever Laziness"
copyright = "2017 Clever Laziness"

googleAnalytics = ""

enableRobotsTXT = "true"

[author]
  name = "Juan"

SectionPagesMenu = "main"

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about/"

[params.meta]
  keywords = "automation, iOS, macOS, web, Apple"
  description = "A blog about automation and productivity"

[params]
  twitter = "cleverlaziness"

[outputs]
  home = ["html", "rss"]

