FootnoteReturnLinkContents = "↩"
SectionPagesMenu = "main"
baseURL = "/"
copyright = " 2018 Four One Eight LLC"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Clever Laziness"

# Pygments Syntax Highlighting
pygmentsUseClassic = false
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=inline, lineseparator=<br>"
pygmentsStyle = "monokai"

[author]
  name = "Juan Villela"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[outputs]
  home = ["html", "rss"]

[params]
  OpenLinksInNewWindow = true
  social = "fourjuaneight"

[params.google.analytics]
  trackerID = "UA-119777735-1"

[params.meta]
  description = "A blog about coding and productivity"
  keywords = "coding, productivity, automation"

[permalinks]
  archive = "/:title/"