# Global settings applied to the whole site.
[build]
  base    = "hugo_0.19"
  publish = "public"
  command = "hugo"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = ""

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = ""
